repo_url: https://github.com/batistagroup/calcflow
repo_name: batistagroup/calcflow
copyright: CC-BY 4.0 &copy; 2025 Batista Group
site_name: CalcFlow Docs
theme:
  name: material
  features:
    - content.code.copy
    
extra_css:
- stylesheets/extra.css

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: true  # Enable source code display
          show_submodules: true
          docstring_style: google  # Or your preferred style
          show_signature: true
          members_order: source  # Order methods as they appear in source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

